### ISSUE TITLE
Add new command to migrate Scrapy projects

### ISSUE THREAD

**Issue by vdusek** [apify/apify-cli#388]
### Summary

We would like to add a new command to migrate existing Scrapy projects to the Apify Platform. The command could be called `apify-cli migrate-from-scrapy "path"` and it would take the path to a Scrapy project as its argument. The command would then wrap the existing Scrapy project with Apify code, which would include additional files and update some settings and configuration files.

### Additional context

The `apify-cli migrate-from-scrapy` command should be able to handle Scrapy projects with many components, such as spiders, item pipelines, middlewares, ... The command should be able to update the settings and configuration files of the Scrapy project to make it compatible with Apify. See the current [Python Scrapy Templated](https://github.com/apify/actor-templates/tree/master/templates/python-scrapy).

### Steps / what needs to be resolved

- [ ] Check the "Hello world" Scrapy project tutorial to learn the basics - https://docs.scrapy.org/en/latest/intro/tutorial.html
- [ ] How to get the path to the `"Scrapy Component"` file(s) and copy it (them)
    - Replace `"Scrapy Component"` with `Spiders`, `Middlewares`,  `Pipelines`, `Items` and maybe others
- [ ] How to merge Python dependencies (`requirements.txt`)
- [ ] How to fill Spider name and path to Spider to the `main.py` (templating?)
- [ ] How to merge settings file (`settings.py`)
- [ ] How to merge Scrapy conf (`scrapy.cfg`)
- [ ] How to let user know that currently only 1 Spider is supported
