### ISSUE TITLE
EPIC: Datasets / Key-Value-Stores Namespace

### ISSUE THREAD

**Issue by netmilk** [apify/apify-cli#623]
* [x] **`datasets`**
```[tasklist]
### Datasets
- [x] `create [--name=<name>]` https://github.com/apify/apify-cli/pull/685
- [x] `ls [--offset=<num>] [--limit=<num>] [--desc] [--unnamed]` https://github.com/apify/apify-cli/pull/685
- [ ] `info <dataset-id>` - Get info about a specific run https://github.com/apify/apify-cli/pull/726
- [x] `rm <dataset-id>` https://github.com/apify/apify-cli/pull/685
- [x] `rename <dataset-id> {<new-name> | --unname} [--force]` https://github.com/apify/apify-cli/pull/685
- [x] `get-items <dataset-id> [--limit=<num>] [--offset=<num>] [--format=<format>]` https://github.com/apify/apify-cli/pull/679
- [x] `push-items <dataset-id> <value>` - supports stdin if no`value` https://github.com/apify/apify-cli/pull/685
```
* [x] **`key-value-stores`**
```[tasklist]
### KVS
- [x] `create [--name=<name>]` https://github.com/apify/apify-cli/pull/685
- [x] `ls [--offset=<num>] [--limit=<num>] [--desc] [--unnamed]` - Lists stores https://github.com/apify/apify-cli/pull/685
- [ ] `info <kvs-id>` - Get info about a specific store https://github.com/apify/apify-cli/pull/726
- [x] `keys <kvs-id> [--exclusive-start-id=<id>] [--limit=<num>]` - List keys and sizes of records, like “list keys” API op https://github.com/apify/apify-cli/pull/700
- [x] `rm <kvs-id>` https://github.com/apify/apify-cli/pull/685
- [x] `rename <kvs-id> { <new-name> | --unname }` https://github.com/apify/apify-cli/pull/685
- [x] `set-value <kvs-id> <key> [value] --content-type=<type>` - If value missing, stdin expected, can be any blob https://github.com/apify/apify-cli/pull/700
- [x] `get-value <kvs-id> <key> [--only-content-type]` - Returns the value to *stdout* and the content-type to *stderr* https://github.com/apify/apify-cli/pull/678
- [x] `delete-value <kvs-id> <key>` https://github.com/apify/apify-cli/pull/700
```
[Internal Notion document](https://www.notion.so/apify/API-CLI-design-Final-Draft-517b46afd5b8431dae7e38b06c9080fc#68bf93c034f84e9d80dcb325805fb875)
