### ISSUE TITLE
EPIC: Request Queue Namespace

### ISSUE THREAD

**Issue by netmilk** [apify/apify-cli#624]
- [ ] **`request-queues`**
```[tasklist]
- [ ] `ls [--limit=<num>] [--offset=<num>] [--format=<format>]`
- [ ] `create --name=<name>`
- [ ] `info <queue-id> [--json]`
- [ ] `update <queue-id> --name=<name>`
- [ ] `rm <queue-id>`
- [ ] `list-requests <queue-id> [--exclusive-start-key=<id>] [--limit=<num>] --clientId=<client-id>]`
- [ ] `add-request <queue-id> {--url=<url> --method=<http-method> | --bulk} [--forefront]  [--clientId=<client-id>]`
- [ ] `remove-request {<request-id> | --bulk}`
- [ ] `get-head <queue-id> --lock`
- [ ] `add-requests <queue-id>`
```

[Internal Notion document](https://www.notion.so/apify/API-CLI-design-Final-Draft-517b46afd5b8431dae7e38b06c9080fc#68bf93c034f84e9d80dcb325805fb875)

**Comment by patrikbraborec** [comment]
Closing — request queue management is covered by the `apify api` command, which provides authenticated access to all request queue endpoints:

```bash
apify api GET /v2/request-queues
apify api POST /v2/request-queues -b '{"name": "my-queue"}'
apify api GET /v2/request-queues/{queueId}/requests
```

Dedicated `request-queues` subcommands may be added later if usage shows demand, but the full functionality is available today via `apify api`.
